"""
analyzer.py — Cipher Analysis Engine v2
========================================
Cipher specializes in: IV rank, options flow, gamma environment.

ARCHITECTURE CHANGE (Apr 15, 2026):
    Score is now computed deterministically by shared/scorer.py.
    Claude's role: write the reasoning explanation ONLY.
    Score is never generated by the LLM — it is pure arithmetic.

    Same data → same score. Always.
"""

import json
import logging
import sys
import os
from typing import Optional

import anthropic

# Shared deterministic scorer
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from shared.scorer import compute_score, determine_direction, build_reasoning_prompt

logger = logging.getLogger("cipher.analyzer")

AGENT_NAME  = "Cipher"
CLAUDE_MODEL = "claude-sonnet-4-6"


def analyze(
    ticker: str,
    context: dict,
    regime: dict,
    anthropic_api_key: str,
) -> Optional[dict]:
    """
    Score a ticker for options trading quality.

    Steps:
        1. Determine direction from hard data (deterministic)
        2. Compute score from lookup tables (deterministic)
        3. Call Claude to write reasoning explanation (LLM — explanation only)
        4. Return {direction, score, reasoning}

    Args:
        ticker:           Stock ticker symbol
        context:          Full Oracle context packet
        regime:           Current market regime from Axiom
        anthropic_api_key: Anthropic API key

    Returns:
        Dict with {direction, score, reasoning} or None on failure.
    """
    if not context:
        logger.warning("No Oracle context for %s — skipping", ticker)
        return None

    try:
        # ── Step 1: Deterministic direction ───────────────────────────────────
        direction = determine_direction(context)

        # ── Step 2: Deterministic score ─────────────────────────────────────────────
        result = compute_score(context, direction)

        # Data completeness gate: if Oracle returned insufficient data, skip
        if result.recommendation == "REJECT" and result.score == 0 and "DATA_GATE" in str(result.gates_fired):
            logger.warning("Cipher skipping %s: insufficient Oracle data (%s)", ticker, result.gates_fired)
            return None

        logger.info(
            "Cipher scored %s: %s %d/100 [D1=%s D2=%s D3=%s D4=%s D5=%s D6=%s] gates=%s",
            ticker, direction, result.score,
            result.breakdown.get("D1_iv_structure", "?"),
            result.breakdown.get("D2_options_flow", "?"),
            result.breakdown.get("D3_technical_setup", "?"),
            result.breakdown.get("D4_earnings_safety", "?"),
            result.breakdown.get("D5_fundamental_quality", "?"),
            result.breakdown.get("D6_gamma_safety", "?"),
            len(result.gates_fired),
        )

        # ── Step 3: LLM writes reasoning only ─────────────────────────────────
        reasoning = _get_reasoning(ticker, result, anthropic_api_key)

        return {
            "direction":    direction,
            "score":        float(result.score),
            "reasoning":    reasoning,
            "breakdown":    result.breakdown,
            "gates_fired":  result.gates_fired,
            "raw_score":    result.raw_score,
            "cap_applied":  result.cap_applied,
            "recommendation": result.recommendation,
        }

    except Exception as e:
        logger.error("Cipher analysis failed for %s: %s", ticker, e)
        return None


def _get_reasoning(ticker: str, result, anthropic_api_key: str) -> str:
    """Call Claude to explain the already-computed score. Max 2 sentences."""
    try:
        client = anthropic.Anthropic(api_key=anthropic_api_key)
        prompt = build_reasoning_prompt(ticker, result)

        response = client.messages.create(
            model      = CLAUDE_MODEL,
            max_tokens = 150,
            temperature= 0.2,   # Low temperature for consistent explanations
            messages   = [{"role": "user", "content": prompt}],
        )
        return response.content[0].text.strip()

    except Exception as e:
        logger.warning("Cipher reasoning call failed for %s: %s", ticker, e)
        # Fallback: generate reasoning from breakdown without LLM
        return _fallback_reasoning(ticker, result)


def _fallback_reasoning(ticker: str, result) -> str:
    """Generate deterministic reasoning text if LLM call fails."""
    bd = result.breakdown
    parts = []

    if result.gates_fired:
        parts.append(result.gates_fired[0].split(":")[0].replace("_", " ").title()
                     + " triggered hard cap")

    strongest = max(result.breakdown, key=result.breakdown.get)
    weakest   = min(result.breakdown, key=result.breakdown.get)
    parts.append(f"Strongest: {strongest.split('_',1)[1].replace('_',' ')} ({bd[strongest]}pts)")
    parts.append(f"Weakest: {weakest.split('_',1)[1].replace('_',' ')} ({bd[weakest]}pts)")

    return (f"Score {result.score}/100 ({result.recommendation}). "
            + ". ".join(parts) + ".")
