"""
analyzer.py — Sage Analysis Engine v2
=======================================
Sage specializes in: earnings risk, fundamentals, macro calendar.

ARCHITECTURE CHANGE (Apr 15, 2026):
    Score is now computed deterministically by shared/scorer.py.
    DeepSeek's role: write the reasoning explanation ONLY.
    Score is never generated by the LLM — it is pure arithmetic.

    Same data → same score. Always.
"""

import json
import logging
import sys
import os
from typing import Optional

import openai

# Shared deterministic scorer
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from shared.scorer import compute_score, determine_direction, build_reasoning_prompt

logger = logging.getLogger("sage.analyzer")

AGENT_NAME         = "Sage"
DEEPSEEK_MODEL     = "deepseek-chat"
EARNINGS_SCORE_CAP = 25   # Score ceiling when earnings are imminent (<7 days) — matches scorer.py EARNINGS_IMMINENT gate


def analyze(
    ticker: str,
    context: dict,
    regime: dict,
    deepseek_api_key: str,
    deepseek_base_url: str = "https://api.deepseek.com/v1",
) -> Optional[dict]:
    """
    Score a ticker for fundamental trade quality.

    Steps:
        1. Determine direction from hard data (deterministic)
        2. Compute score from lookup tables (deterministic)
        3. Call DeepSeek to write reasoning explanation (LLM — explanation only)
        4. Return {direction, score, reasoning}

    Args:
        ticker:            Stock ticker symbol
        context:           Full Oracle context packet
        regime:            Current market regime from Axiom
        deepseek_api_key:  DeepSeek API key
        deepseek_base_url: DeepSeek API base URL

    Returns:
        Dict with {direction, score, reasoning} or None on failure.
    """
    if not context:
        logger.warning("No Oracle context for %s — skipping", ticker)
        return None

    try:
        # ── Step 1: Deterministic direction ───────────────────────────────────
        direction = determine_direction(context)

        # ── Step 2: Deterministic score ───────────────────────────────────────
        result = compute_score(context, direction)

        # Data completeness gate: if Oracle returned insufficient data, skip
        if result.recommendation == "REJECT" and result.score == 0 and "DATA_GATE" in str(result.gates_fired):
            import logging as _log; _log.getLogger("sage.analyzer").warning("sage skipping %s: insufficient Oracle data (%s)", ticker, result.gates_fired)
            return None

        logger.info(
            "Sage scored %s: %s %d/100 [D1=%d D2=%d D3=%d D4=%d D5=%d D6=%d] gates=%s",
            ticker, direction, result.score,
            result.breakdown["D1_iv_structure"],
            result.breakdown["D2_options_flow"],
            result.breakdown["D3_technical_setup"],
            result.breakdown["D4_earnings_safety"],
            result.breakdown["D5_fundamental_quality"],
            result.breakdown["D6_gamma_safety"],
            len(result.gates_fired),
        )

        # ── Step 3: LLM writes reasoning only ─────────────────────────────────
        reasoning = _get_reasoning(ticker, result, deepseek_api_key, deepseek_base_url)

        return {
            "direction":    direction,
            "score":        float(result.score),
            "reasoning":    reasoning,
            "breakdown":    result.breakdown,
            "gates_fired":  result.gates_fired,
            "raw_score":    result.raw_score,
            "cap_applied":  result.cap_applied,
            "recommendation": result.recommendation,
        }

    except Exception as e:
        logger.error("Sage analysis failed for %s: %s", ticker, e)
        return None


def _get_reasoning(
    ticker: str, result, deepseek_api_key: str, deepseek_base_url: str
) -> str:
    """Call DeepSeek to explain the already-computed score. Max 2 sentences."""
    try:
        client = openai.OpenAI(api_key=deepseek_api_key, base_url=deepseek_base_url)
        prompt = build_reasoning_prompt(ticker, result)

        response = client.chat.completions.create(
            model       = DEEPSEEK_MODEL,
            max_tokens  = 150,
            temperature = 0.1,
            messages    = [{"role": "user", "content": prompt}],
        )
        return response.choices[0].message.content.strip()

    except Exception as e:
        logger.warning("Sage reasoning call failed for %s: %s", ticker, e)
        return _fallback_reasoning(ticker, result)


def _fallback_reasoning(ticker: str, result) -> str:
    bd = result.breakdown
    parts = []
    if result.gates_fired:
        parts.append(result.gates_fired[0].split(":")[0].replace("_", " ").title()
                     + " triggered hard cap")
    strongest = max(bd, key=bd.get)
    weakest   = min(bd, key=bd.get)
    parts.append(f"Strongest: {strongest.split('_',1)[1].replace('_',' ')} ({bd[strongest]}pts)")
    parts.append(f"Weakest: {weakest.split('_',1)[1].replace('_',' ')} ({bd[weakest]}pts)")
    return (f"Score {result.score}/100 ({result.recommendation}). "
            + ". ".join(parts) + ".")
