"""
analyzer.py — Atlas Analysis Engine v2
========================================
Atlas specializes in: technical structure, momentum, gamma levels.

ARCHITECTURE CHANGE (Apr 15, 2026):
    Score is now computed deterministically by shared/scorer.py.
    Gemini's role: write the reasoning explanation ONLY.
    Score is never generated by the LLM — it is pure arithmetic.

    Same data → same score. Always.
"""

import json
import logging
import sys
import os
import time
from typing import Optional

import google.generativeai as genai

# Shared deterministic scorer
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from shared.scorer import compute_score, determine_direction, build_reasoning_prompt

logger = logging.getLogger("atlas.analyzer")

AGENT_NAME            = "Atlas"
GEMINI_MODEL_PRIMARY  = "gemini-2.5-flash-preview-04-17"
GEMINI_MODEL_FALLBACK = "gemini-2.5-pro-preview-03-25"


def analyze(
    ticker: str,
    context: dict,
    regime: dict,
    echo_chamber_risk: list,
    gemini_api_key: str,
) -> Optional[dict]:
    """
    Score a ticker for technical trade quality.

    Steps:
        1. Determine direction from hard data (deterministic)
        2. Compute score from lookup tables (deterministic)
        3. Call Gemini to write reasoning explanation (LLM — explanation only)
        4. Return {direction, score, reasoning}

    Args:
        ticker:            Stock ticker symbol
        context:           Full Oracle context packet
        regime:            Current market regime from Axiom
        echo_chamber_risk: List of over-watched tickers (retained for compatibility)
        gemini_api_key:    Gemini API key

    Returns:
        Dict with {direction, score, reasoning} or None on failure.
    """
    if not context:
        logger.warning("No Oracle context for %s — skipping", ticker)
        return None

    try:
        # ── Step 1: Deterministic direction ───────────────────────────────────
        direction = determine_direction(context)

        # ── Step 2: Deterministic score ───────────────────────────────────────
        result = compute_score(context, direction)

        # Data completeness gate: if Oracle returned insufficient data, skip
        if result.recommendation == "REJECT" and result.score == 0 and "DATA_GATE" in str(result.gates_fired):
            import logging as _log; _log.getLogger("atlas.analyzer").warning("atlas skipping %s: insufficient Oracle data (%s)", ticker, result.gates_fired)
            return None

        logger.info(
            "Atlas scored %s: %s %d/100 [D1=%d D2=%d D3=%d D4=%d D5=%d D6=%d] gates=%s",
            ticker, direction, result.score,
            result.breakdown["D1_iv_structure"],
            result.breakdown["D2_options_flow"],
            result.breakdown["D3_technical_setup"],
            result.breakdown["D4_earnings_safety"],
            result.breakdown["D5_fundamental_quality"],
            result.breakdown["D6_gamma_safety"],
            len(result.gates_fired),
        )

        # ── Step 3: LLM writes reasoning only ─────────────────────────────────
        reasoning = _get_reasoning(ticker, result, gemini_api_key)

        return {
            "direction":    direction,
            "score":        float(result.score),
            "reasoning":    reasoning,
            "breakdown":    result.breakdown,
            "gates_fired":  result.gates_fired,
            "raw_score":    result.raw_score,
            "cap_applied":  result.cap_applied,
            "recommendation": result.recommendation,
        }

    except Exception as e:
        logger.error("Atlas analysis failed for %s: %s", ticker, e)
        return None


def _get_reasoning(ticker: str, result, gemini_api_key: str) -> str:
    """Call Gemini to explain the already-computed score. Max 2 sentences."""
    try:
        genai.configure(api_key=gemini_api_key)
        prompt = build_reasoning_prompt(ticker, result)

        for model_name in [GEMINI_MODEL_PRIMARY, GEMINI_MODEL_FALLBACK]:
            try:
                model    = genai.GenerativeModel(model_name)
                response = model.generate_content(
                    prompt,
                    request_options={"timeout": 20},
                    generation_config=genai.GenerationConfig(
                        max_output_tokens=150,
                        temperature=0.1,
                    ),
                )
                return response.text.strip()
            except Exception:
                time.sleep(1)
                continue

        return _fallback_reasoning(ticker, result)

    except Exception as e:
        logger.warning("Atlas reasoning call failed for %s: %s", ticker, e)
        return _fallback_reasoning(ticker, result)


def _fallback_reasoning(ticker: str, result) -> str:
    bd = result.breakdown
    parts = []
    if result.gates_fired:
        parts.append(result.gates_fired[0].split(":")[0].replace("_", " ").title()
                     + " triggered hard cap")
    strongest = max(bd, key=bd.get)
    weakest   = min(bd, key=bd.get)
    parts.append(f"Strongest: {strongest.split('_',1)[1].replace('_',' ')} ({bd[strongest]}pts)")
    parts.append(f"Weakest: {weakest.split('_',1)[1].replace('_',' ')} ({bd[weakest]}pts)")
    return (f"Score {result.score}/100 ({result.recommendation}). "
            + ". ".join(parts) + ".")


def build_prompt(ticker: str, context: dict, regime: dict, echo_chamber_risk: list) -> str:
    """
    Build a structured analysis prompt for Atlas.

    Exported for testing and legacy callers. In v2, Atlas uses deterministic scoring
    (compute_score) and calls Gemini only for reasoning explanation (_get_reasoning).
    This function provides a human-readable prompt representation for inspection.

    Args:
        ticker: Stock ticker symbol.
        context: Oracle context packet (may be empty in tests).
        regime: Current market regime dict with 'classification' key.
        echo_chamber_risk: List of over-watched tickers.

    Returns:
        Prompt string describing the analysis task, including echo chamber warning if applicable.
    """
    is_echo = ticker in echo_chamber_risk
    regime_label = regime.get("classification", "UNKNOWN") if regime else "UNKNOWN"
    echo_note = (
        "⚠️ OVER-WATCHED TICKER (echo chamber risk — apply -10pt penalty to final score)"
        if is_echo
        else "Not flagged as over-watched."
    )
    return (
        f"Analyze {ticker} for a technical trade setup.\n"
        f"Regime: {regime_label}\n"
        f"Echo chamber status: {echo_note}\n"
        f"Provide direction (bullish/bearish/neutral), score (0-100), and reasoning."
    )
